---
# handlers file for deploy_alermanager
- name: restart alertmanager
  service:
     name: alertmanager
     state: restarted
     enabled: true
- name: restart prometheus
  service:
      name: prometheus
      enabled: true
      state: restarted

