---
# tasks file for deploy_loadbalancer
- name: Create nginx group
  group:
    name: "{{ nginx_group }}"
    state: present

- name: Create nginx user
  user:
    name: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    home: "{{ nginx_working_dir }}"
    createhome: false
    shell: /bin/bash

- name: Upload config file for load balancer
  template:
    src: loadbalancer.conf.j2
    dest: "{{ nginx_confd }}/loadbalancer.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Connect nginx to httpd
  ansible.builtin.command: setsebool -P httpd_can_network_connect 1

